plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.polet.diman'
    compileSdk 34

    defaultConfig {
        applicationId "ru.polet.diman"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        release {
            storeFile file('diman.keystore')
            storePassword 'diman2026'
            keyAlias 'diman'
            keyPassword 'diman2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.9.24'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.24'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.24'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
}
